### ISSUE TITLE
Illstack Search Radius

### ISSUE THREAD

**Issue by marcelo-alvarez** [marcelo-alvarez/illstack#7]
from @emilymmoser:

Adjusting the value of parameter "search_radius", defined in illstack/params.py then used in illstack/cyprof.pyx that is used for the periodic boundary conditions in the function cyprof/add_ghost_particles to values of
`  search_radius = [10, 20, 50]`
results in profiles that begin to differ at 
`  rmax ~ [1.6, 3.2, 8] Mpc`
Since the maximum rh used for the rbuff calculation in the function cyprof/stackonhalos is about rhmax ~ 1 Mpc
one should expect 
```
  rmax ~ search_radius * rhmax
       ~ [10, 20, 50] Mpc
```
instead.

**Comment by emilymmoser** [comment]
Fixed by changing rh[ih] to rpmax in CHP loop of illstack/cyprof/stackonhalostile
